
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    # depends_on:
    #   - mongo
    volumes:
      - ./backend:/usr/src/app   # Monta tu código en el contenedor
      - /usr/src/app/node_modules # Evita conflictos de dependencias
    networks:
      - support-app-network
    env_file:
      - ./backend/.env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - support-app-network


  frontend:
    build:
      context: ./frontend   # Aquí va la carpeta donde está tu proyecto Vite
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run dev -- --host 0.0.0.0   # Para exponer el dev server
    networks:
      - support-app-network

volumes:
  pgdata:

networks:
  support-app-network: